### Get all tiles
GET http://localhost:8080/tile


### Create a tile
PATCH http://localhost:8080/tile
Content-Type: application/json

{
    "added": [
        {
            "color": "#90AACB",
            "id": "61efeef69cfa28fffd7faa8d"
        }
    ],
    "changed": [
        {
            "id": "61ebee07315de8b9124b1029",
            "color": "#FFB085"
        }
    ],
    "deleted": ["61e9e4af06ef5968267e8e2b"]
}
