### Get all tiles
GET http://localhost:8080/tile


### Create a tile
PATCH http://localhost:8080/tile
Content-Type: application/json

{
    "changed": [
        {
            "color": "#90AACB",
            "_id": "61e9e4af06ef5968267e8e2b"
        }
    ],
    "added": [],
    "deleted": []
}
